
#CALCULO DE UNA RAIZ CUADRADA
import math #IMPORTAMOS LA CLASE math PARA HACER USO DEL METODO SQRT PARA EL CALCULO DE UNA RAIZ CUADRADA

numero = int(input("Ingrese numero a calcular: "))#INGRESAMOS EL NUMERO A CALCULAR
cont = 1#INICIAMOS EL CONTADOR

while numero < 0:#EJECUTAMOS MIENTRAS EL VALOR INGRESADO SEA UN VALOR MENOR A CERO O NUMERO NEGATIVO

    print("IngresÓ un numero negativo")#INFORMAMOS QUE SE INGRESO UN NUMERO NEGATIVO
    numero = int(input("Ingrese nuevamente el numero "))#GUARDAMOS EN UNA VARIABLE EL NUMERO NUEVAMENTE

    if cont >=3:#VALIDAMOS QUE EL CONTADOR ALCANCE EL VALOR DE 3
        print(f"Alcanzaste el numero maximo de {cont} intentos")#INFORMAMOS QUE ALCANZO EL NUMERO MAXIMO DE INTENTOS
        break#ROMPEMOS EL FLUJO DE EJECUCION
    else:#EN CASO CONTRARIO
        cont+=1#INCRENTAMOS EL CONTADOR


if numero > 0:#VALIDAMOS SI EL NUMERO ES MAYOR QUE 0 PARA CALCULAR LA RAIZ CUADRADA
    resultado = math.sqrt(numero)#CREAMOS UNA VARIABLE A LA QUE LE ASIGNAMOS EL RESULTADO DEL CALCULO DE LA RAIZ CUADRADA
    print(f"La raiz cuadrada de {numero} es {resultado}")#INFORMAMOS EL RESULTADO DE LA FUNCION RAIZ CUADRADA
else:#EN CASO CONTRARIO
    print("El valor ingresado es incorrecto")#INFORMAMOS QUE SE HA INGRESADO UN VALOR INCORRECTO


    
