print ("hola mundo")

#TIPOS DE DATOS EN PYTHON
PYTHON ES CASE SENSITIVE
TIPOS DE DATOS

STRING "...", '...', """...""", '''...'''

COMANDO TYPE PERMITE IMPRMIR EL TIPO DE DATO DE UN VALOR

UNIR O CONCATENAR STRING:

"Palabra 1" + "Palabra 2"

->int,
->float,
->boolean,
-->None
->LIST(LISTAR DATOS) EJEMPLO --> [10,"20",true,10.1]; SE PUEDEN COMPLETAR DISTINTOS TIPOS DE DATOS. SE DEBEN COLOCAR ENTRE CORCHETES

->TUPLAS-> AGRUPA DATOS QUE NO PUEDEN CAMBIAR SE DEBEN COLOCAR ENTRE PARENTESIS

->DICCIONARIOS--> AGRUPA DISTINTOS TIPOS DE DATOS QUE PERTENECEN A UNA MISMA ENTIDAD Y SE DEBEN COLOCAR ENTRE LLAVES EJEMPLO {NOMBRE:VALOR}, 

####################################################

-> VARIABLES: PERMITE ALMACENAR VALORES DE CUALQUIER TIPO






